import type { Database } from "@/types/database.types";
import styles from "./body-map.module.css";

export type MuscleGroup = Database["public"]["Enums"]["muscle_group"];

export const MUSCLE_LABELS: Record<MuscleGroup, string> = {
  traps: "Trapezius",
  shoulders: "Shoulders",
  chest: "Chest",
  biceps: "Biceps",
  triceps: "Triceps",
  forearms: "Forearms",
  abdominals: "Abdominals",
  obliques: "Obliques",
  upper_back: "Upper back",
  lats: "Lats",
  lower_back: "Lower back",
  glutes: "Glutes",
  quadriceps: "Quadriceps",
  hamstrings: "Hamstrings",
  calves: "Calves",
};

type Figure = "male" | "female";
type View = "front" | "back";

/* ── Geometry ─────────────────────────────────────────────────────────
 * Both figures are authored once as cubic bezier paths on a 300 × 640
 * canvas (centre line x = 150) for the male frame. The female frame is
 * the same drawing passed through a piecewise horizontal scale around
 * the centre line: narrower shoulders and waist, wider hips. */

type Pt = readonly [number, number];
type Seg = { c1: Pt; c2: Pt; to: Pt };

const CX = 150;

/** seg(c1x, c1y, c2x, c2y, x, y) — one cubic segment. */
function seg(c1x: number, c1y: number, c2x: number, c2y: number, x: number, y: number): Seg {
  return { c1: [c1x, c1y], c2: [c2x, c2y], to: [x, y] };
}

/* Horizontal scale by height for the female frame (1 = male width). */
const FEMALE_STOPS: readonly Pt[] = [
  [0, 1],
  [70, 1],
  [115, 0.9],
  [200, 0.88],
  [270, 0.85],
  [310, 0.96],
  [350, 1.07],
  [405, 1.05],
  [475, 1],
  [640, 0.96],
];

function scaleAt(y: number, figure: Figure): number {
  if (figure === "male") return 1;
  const stops = FEMALE_STOPS;
  if (y <= stops[0]![1]) return stops[0]![1];
  for (let i = 1; i < stops.length; i += 1) {
    const [y1, s1] = stops[i]!;
    const [y0, s0] = stops[i - 1]!;
    if (y <= y1) return s0 + ((y - y0) / (y1 - y0)) * (s1 - s0);
  }
  return stops[stops.length - 1]![1];
}

function tx(p: Pt, figure: Figure): Pt {
  return [CX + (p[0] - CX) * scaleAt(p[1], figure), p[1]];
}

function mir(p: Pt): Pt {
  return [2 * CX - p[0], p[1]];
}

function fmt(p: Pt): string {
  return `${p[0].toFixed(1)} ${p[1].toFixed(1)}`;
}

/** A plain path from authored points, shaped for the figure. */
function pathFrom(start: Pt, segs: Seg[], figure: Figure, close: boolean): string {
  const t = (p: Pt) => tx(p, figure);
  let d = `M ${fmt(t(start))}`;
  for (const s of segs) d += ` C ${fmt(t(s.c1))} ${fmt(t(s.c2))} ${fmt(t(s.to))}`;
  return close ? `${d} Z` : d;
}

/** The same shape mirrored to the other side of the body. */
function mirrored(start: Pt, segs: Seg[]): { start: Pt; segs: Seg[] } {
  return {
    start: mir(start),
    segs: segs.map((s) => ({ c1: mir(s.c1), c2: mir(s.c2), to: mir(s.to) })),
  };
}

/** Symmetric closed path: author the left half from a centre-line start to a
 * centre-line end; the right half is generated by mirroring back. */
function symPath(start: Pt, segs: Seg[], figure: Figure): string {
  const t = (p: Pt) => tx(p, figure);
  let d = `M ${fmt(t(start))}`;
  for (const s of segs) d += ` C ${fmt(t(s.c1))} ${fmt(t(s.c2))} ${fmt(t(s.to))}`;
  const anchors: Pt[] = [start, ...segs.map((s) => s.to)];
  for (let i = segs.length - 1; i >= 0; i -= 1) {
    const s = segs[i]!;
    d += ` C ${fmt(t(mir(s.c2)))} ${fmt(t(mir(s.c1)))} ${fmt(t(mir(anchors[i]!)))}`;
  }
  return `${d} Z`;
}

/* ── The body outline (same posture front and back) ───────────────────
 * Left half, crown → left arm → left leg → crotch; mirrored to close. */
const OUTLINE_START: Pt = [150, 10];
const OUTLINE: Seg[] = [
  seg(138, 10, 124, 14, 118, 26), // crown → temple
  seg(114, 38, 117, 50, 126, 58), // temple → jaw
  seg(131, 62, 134, 64, 135, 70), // jaw → neck top
  seg(135, 76, 134, 80, 133, 84), // short neck
  seg(116, 92, 98, 96, 84, 102), // neck → shoulder tip
  seg(73, 108, 66, 114, 64, 126), // shoulder corner
  seg(62, 136, 61, 146, 60, 158), // deltoid outer edge
  seg(58, 186, 57, 212, 56, 235), // upper arm → elbow outer
  seg(52, 264, 47, 296, 44, 322), // forearm → wrist outer
  seg(41, 338, 37, 354, 36, 368), // wrist → fingertips
  seg(37, 377, 44, 381, 49, 376), // around the fingertips
  seg(56, 371, 61, 352, 63, 336), // hand inner edge
  seg(64, 333, 64, 330, 64, 328), // → wrist inner
  seg(69, 300, 74, 270, 78, 242), // forearm inner → elbow inner
  seg(84, 214, 91, 184, 97, 158), // upper arm inner → armpit
  seg(99, 168, 100, 178, 101, 190), // armpit hollow
  seg(103, 216, 105, 240, 106, 262), // chest side → waist
  seg(103, 286, 98, 306, 95, 325), // waist → hip
  seg(88, 352, 86, 372, 87, 392), // hip → outer thigh
  seg(90, 424, 97, 448, 104, 466), // thigh → outer knee
  seg(108, 486, 103, 506, 98, 524), // knee → calf bulge
  seg(96, 548, 104, 568, 113, 582), // calf → outer ankle
  seg(116, 596, 104, 606, 95, 614), // ankle → toes
  seg(92, 622, 106, 626, 118, 624), // toe cap
  seg(128, 622, 133, 616, 133, 606), // foot inner → heel
  seg(133, 598, 133, 592, 133, 586), // heel → inner ankle
  seg(128, 560, 126, 540, 128, 520), // inner calf bulge
  seg(131, 502, 134, 486, 136, 472), // → inner knee
  seg(139, 448, 144, 420, 147, 400), // inner thigh
  seg(148, 394, 149, 389, 150, 385), // → crotch
];

type ShapeDef = { start: Pt; segs: Seg[] };
type MuscleDef = { muscle: MuscleGroup; shape: ShapeDef; sym?: boolean };

/* ── Front compartments ──────────────────────────────────────────────── */
const FRONT_MUSCLES: MuscleDef[] = [
  {
    muscle: "traps",
    shape: {
      start: [137, 80],
      segs: [
        seg(120, 84, 103, 92, 92, 103),
        seg(105, 103, 122, 96, 137, 90),
        seg(138, 86, 138, 83, 137, 80),
      ],
    },
  },
  {
    muscle: "shoulders",
    shape: {
      start: [92, 104],
      segs: [
        seg(76, 108, 66, 124, 68, 146),
        seg(70, 158, 82, 158, 90, 148),
        seg(97, 134, 99, 114, 92, 104),
      ],
    },
  },
  {
    muscle: "chest",
    shape: {
      start: [148, 116],
      segs: [
        seg(128, 112, 106, 116, 98, 128),
        seg(94, 146, 102, 166, 120, 176),
        seg(136, 182, 147, 174, 148, 158),
        seg(149, 144, 149, 130, 148, 116),
      ],
    },
  },
  {
    muscle: "biceps",
    shape: {
      start: [78, 158],
      segs: [
        seg(68, 170, 64, 192, 66, 218),
        seg(68, 234, 74, 242, 81, 236),
        seg(86, 222, 87, 196, 85, 174),
        seg(83, 160, 80, 155, 78, 158),
      ],
    },
  },
  {
    muscle: "forearms",
    shape: {
      start: [60, 248],
      segs: [
        seg(54, 272, 50, 300, 52, 324),
        seg(55, 334, 63, 332, 67, 322),
        seg(71, 298, 72, 274, 70, 252),
        seg(66, 242, 62, 242, 60, 248),
      ],
    },
  },
  {
    muscle: "abdominals",
    sym: true,
    shape: {
      start: [150, 186],
      segs: [
        seg(141, 185, 133, 186, 129, 191),
        seg(125, 232, 126, 280, 133, 314),
        seg(138, 330, 146, 334, 150, 334),
      ],
    },
  },
  {
    muscle: "obliques",
    shape: {
      start: [125, 200],
      segs: [
        seg(115, 206, 108, 216, 106, 232),
        seg(104, 262, 107, 292, 114, 318),
        seg(119, 325, 125, 322, 126, 312),
        seg(122, 276, 121, 236, 125, 200),
      ],
    },
  },
  {
    muscle: "quadriceps",
    shape: {
      start: [103, 352],
      segs: [
        seg(92, 376, 88, 412, 92, 444),
        seg(96, 466, 107, 472, 117, 462),
        seg(126, 442, 128, 404, 124, 376),
        seg(118, 354, 110, 346, 103, 352),
      ],
    },
  },
  {
    muscle: "calves",
    shape: {
      start: [107, 496],
      segs: [
        seg(100, 518, 98, 546, 102, 568),
        seg(106, 580, 114, 578, 118, 566),
        seg(122, 542, 122, 518, 117, 500),
        seg(113, 490, 110, 490, 107, 496),
      ],
    },
  },
];

/* ── Back compartments ───────────────────────────────────────────────── */
const BACK_MUSCLES: MuscleDef[] = [
  {
    muscle: "traps",
    sym: true,
    shape: {
      start: [150, 74],
      segs: [seg(132, 79, 112, 90, 94, 104), seg(112, 128, 136, 166, 150, 198)],
    },
  },
  {
    muscle: "shoulders",
    shape: {
      start: [92, 104],
      segs: [
        seg(76, 108, 66, 124, 68, 146),
        seg(70, 158, 82, 158, 90, 148),
        seg(97, 134, 99, 114, 92, 104),
      ],
    },
  },
  {
    muscle: "upper_back",
    shape: {
      start: [112, 150],
      segs: [
        seg(102, 158, 98, 172, 102, 186),
        seg(108, 197, 122, 196, 129, 184),
        seg(132, 170, 127, 156, 118, 148),
        seg(115, 147, 113, 148, 112, 150),
      ],
    },
  },
  {
    muscle: "triceps",
    shape: {
      start: [78, 160],
      segs: [
        seg(69, 172, 65, 194, 67, 220),
        seg(69, 236, 77, 242, 84, 235),
        seg(89, 218, 89, 192, 86, 174),
        seg(84, 162, 81, 156, 78, 160),
      ],
    },
  },
  {
    muscle: "forearms",
    shape: {
      start: [60, 248],
      segs: [
        seg(54, 272, 50, 300, 52, 324),
        seg(55, 334, 63, 332, 67, 322),
        seg(71, 298, 72, 274, 70, 252),
        seg(66, 242, 62, 242, 60, 248),
      ],
    },
  },
  {
    muscle: "lats",
    shape: {
      start: [110, 196],
      segs: [
        seg(100, 208, 96, 232, 100, 258),
        seg(105, 280, 118, 296, 132, 302),
        seg(139, 286, 141, 254, 137, 228),
        seg(131, 208, 120, 196, 110, 196),
      ],
    },
  },
  {
    muscle: "lower_back",
    sym: true,
    shape: {
      start: [150, 244],
      segs: [
        seg(144, 243, 139, 244, 137, 248),
        seg(133, 276, 135, 302, 143, 320),
        seg(146, 325, 148, 326, 150, 326),
      ],
    },
  },
  {
    muscle: "glutes",
    shape: {
      start: [107, 330],
      segs: [
        seg(95, 340, 91, 360, 97, 380),
        seg(105, 396, 124, 400, 138, 391),
        seg(146, 378, 146, 356, 138, 341),
        seg(127, 329, 115, 326, 107, 330),
      ],
    },
  },
  {
    muscle: "hamstrings",
    shape: {
      start: [101, 406],
      segs: [
        seg(94, 428, 92, 452, 96, 466),
        seg(101, 477, 114, 478, 121, 466),
        seg(127, 448, 127, 426, 122, 412),
        seg(114, 398, 106, 398, 101, 406),
      ],
    },
  },
  {
    muscle: "calves",
    shape: {
      start: [104, 496],
      segs: [
        seg(97, 516, 97, 544, 103, 566),
        seg(108, 578, 117, 576, 121, 562),
        seg(125, 540, 124, 516, 118, 498),
        seg(112, 488, 107, 488, 104, 496),
      ],
    },
  },
];

/* ── Detail strokes (open lines, decorative) ─────────────────────────── */
type DetailDef = { start: Pt; segs: Seg[]; paired?: boolean };

const FRONT_DETAILS: DetailDef[] = [
  // hairline
  { start: [122, 34], segs: [seg(129, 15, 171, 15, 178, 34)] },
  // clavicles
  { start: [100, 110], segs: [seg(116, 116, 132, 118, 146, 118)], paired: true },
  // abdominal segment lines
  { start: [131, 222], segs: [seg(141, 226, 159, 226, 169, 222)] },
  { start: [131, 252], segs: [seg(141, 256, 159, 256, 169, 252)] },
  { start: [132, 282], segs: [seg(142, 286, 158, 286, 168, 282)] },
  // linea alba
  { start: [150, 188], segs: [seg(150, 236, 150, 284, 150, 330)] },
  // knees
  { start: [110, 474], segs: [seg(115, 481, 125, 481, 130, 474)], paired: true },
];

const BACK_DETAILS: DetailDef[] = [
  // spine
  { start: [150, 204], segs: [seg(150, 242, 150, 280, 150, 320)] },
  // elbow
  { start: [60, 242], segs: [seg(64, 248, 70, 248, 74, 242)], paired: true },
  // knee fold
  { start: [110, 478], segs: [seg(115, 484, 125, 484, 130, 478)], paired: true },
  // calf split
  { start: [112, 500], segs: [seg(112, 522, 112, 542, 112, 560)], paired: true },
];

/* Back-of-head hair, drawn as a filled patch. */
const HAIR_BACK: ShapeDef = {
  start: [150, 10],
  segs: [
    seg(136, 10, 124, 16, 122, 28),
    seg(120, 40, 122, 50, 128, 55),
    seg(135, 60, 143, 61, 150, 61),
  ],
};

function MuscleShape({
  def,
  figure,
  kind,
}: {
  def: MuscleDef;
  figure: Figure;
  kind: "primary" | "secondary" | null;
}) {
  const cls = `${styles.muscle} ${kind === "primary" ? styles.primary : ""} ${
    kind === "secondary" ? styles.secondary : ""
  }`;
  if (def.sym) {
    return (
      <g className={cls}>
        <title>{MUSCLE_LABELS[def.muscle]}</title>
        <path d={symPath(def.shape.start, def.shape.segs, figure)} />
      </g>
    );
  }
  const m = mirrored(def.shape.start, def.shape.segs);
  return (
    <g className={cls}>
      <title>{MUSCLE_LABELS[def.muscle]}</title>
      <path d={pathFrom(def.shape.start, def.shape.segs, figure, true)} />
      <path d={pathFrom(m.start, m.segs, figure, true)} />
    </g>
  );
}

function FigureView({
  view,
  figure,
  primary,
  secondary,
}: {
  view: View;
  figure: Figure;
  primary: Set<MuscleGroup>;
  secondary: Set<MuscleGroup>;
}) {
  const muscles = view === "front" ? FRONT_MUSCLES : BACK_MUSCLES;
  const details = view === "front" ? FRONT_DETAILS : BACK_DETAILS;

  return (
    <figure className={styles.figure}>
      <svg viewBox="0 0 300 640" role="img" aria-label={`${view} view of the body`}>
        <path className={styles.body} d={symPath(OUTLINE_START, OUTLINE, figure)} />
        {view === "back" ? (
          <path className={styles.hair} d={symPath(HAIR_BACK.start, HAIR_BACK.segs, figure)} />
        ) : null}
        {muscles.map((def) => (
          <MuscleShape
            key={`${def.muscle}-${view}`}
            def={def}
            figure={figure}
            kind={
              primary.has(def.muscle)
                ? "primary"
                : secondary.has(def.muscle)
                  ? "secondary"
                  : null
            }
          />
        ))}
        {details.map((d, i) => (
          <g key={i} className={styles.detail}>
            <path d={pathFrom(d.start, d.segs, figure, false)} />
            {d.paired ? (
              <path
                d={pathFrom(mirrored(d.start, d.segs).start, mirrored(d.start, d.segs).segs, figure, false)}
              />
            ) : null}
          </g>
        ))}
      </svg>
      <figcaption className={styles.viewLabel}>{view === "front" ? "Front" : "Back"}</figcaption>
    </figure>
  );
}

/**
 * Muscles-worked body map (front and back views, male or female figure).
 * Every compartment is drawn as anatomical line art; the ones this session
 * works are filled (amber = worked directly, slate = also involved). Status
 * rule applies here too: the legend always names the groups in text.
 */
export function BodyMap({
  primary,
  secondary = [],
  figure = "male",
}: {
  primary: MuscleGroup[];
  secondary?: MuscleGroup[];
  figure?: Figure;
}) {
  const primarySet = new Set(primary);
  // A muscle that is primary anywhere in the session shows as primary.
  const secondarySet = new Set(secondary.filter((m) => !primarySet.has(m)));
  const names = (set: Set<MuscleGroup>) =>
    Array.from(set)
      .map((m) => MUSCLE_LABELS[m])
      .join(", ");

  return (
    <div className={styles.wrap}>
      <div className={styles.figures}>
        <FigureView view="front" figure={figure} primary={primarySet} secondary={secondarySet} />
        <FigureView view="back" figure={figure} primary={primarySet} secondary={secondarySet} />
      </div>
      <dl className={styles.legend}>
        {primarySet.size > 0 ? (
          <div className={styles.legendRow}>
            <dt className={styles.legendTerm}>
              <span className={`${styles.legendDot} ${styles.legendDotPrimary}`} aria-hidden="true" />
              Worked directly
            </dt>
            <dd className={styles.legendNames}>{names(primarySet)}</dd>
          </div>
        ) : null}
        {secondarySet.size > 0 ? (
          <div className={styles.legendRow}>
            <dt className={styles.legendTerm}>
              <span
                className={`${styles.legendDot} ${styles.legendDotSecondary}`}
                aria-hidden="true"
              />
              Also involved
            </dt>
            <dd className={styles.legendNames}>{names(secondarySet)}</dd>
          </div>
        ) : null}
        {primarySet.size === 0 && secondarySet.size === 0 ? (
          <p className={styles.legendEmpty}>No muscle groups highlighted.</p>
        ) : null}
      </dl>
    </div>
  );
}
